language: ruby

before_install:
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH=$HOME/.evm/bin:$PATH

  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip

cache:
  directories:
  - /usr/local/evm

env:
  #- EVM_EMACS=emacs-23.4-travis
  #- EVM_EMACS=emacs-24.1-travis
  #- EVM_EMACS=emacs-24.2-travis
  #- EVM_EMACS=emacs-24.3-travis
  #- EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  #- EVM_EMACS=emacs-git-snapshot-travis

script:
  ./run-travis-ci.sh
